name: DevOps / CI Failure Alert

on:
  workflow_run:
    workflows:
      - CI
      - Self Test
      - DevOps / Security
    types: [completed]

jobs:
  alert:
    if: github.event.workflow_run.conclusion == 'failure'
    uses: FelipeFuhr/ffreis-workflows-general/.github/workflows/general-workflow-failure-alert.yml@82097e621b8f630f2be2f759025529f7f5442796 # v1.9.0
    permissions:
      pull-requests: write
